version: '3.3'

services:
  robot_array_visualization:
    image: robot_array_visualization:humble
    user: root
    container_name: robot_array_visualization
    build:
      context: ..
      dockerfile: ./dockerfiles/Dockerfile
    volumes:
      - "../:/root/catkin_ws/src/"
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - "/tmp/.docker.xauth:/tmp/.docker.xauth"
    environment:
      - "DISPLAY=$DISPLAY"
      - "XAUTHORITY=/tmp/.docker.xauth"
      - "QT_X11_NO_MITSHM=1"
    privileged: True
    tty: True
    stdin_open: True
    network_mode: host
    command: bash
